import { jsPDF } from "jspdf";

export function downloadReportPDF(report: any) {
    console.log("NEW PDF SERVICE");
    console.log(report);
    const pdf = new jsPDF();

    let y = 20;

    // Title
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.text("InsightForge AI", 20, y);

    y += 10;

    pdf.setFontSize(16);
    pdf.text("Business Intelligence Report", 20, y);

    y += 15;

    // Executive Summary
    pdf.setFontSize(15);
    pdf.setFont("helvetica", "bold");
    pdf.text("Executive Summary", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    const summary = pdf.splitTextToSize(
        report.executive_summary,
        170
    );

    pdf.text(summary, 20, y);

    y += summary.length * 6 + 10;

    // Dataset Overview
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Dataset Overview", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    Object.entries(report.statistics).forEach(([key, value]) => {
        pdf.text(`${key}: ${value}`, 25, y);
        y += 7;
    });

    y += 5;

    // AI Insights
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("AI Insights", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");

    report.insights.forEach((item: string) => {
        const lines = pdf.splitTextToSize(`• ${item}`, 165);
        pdf.text(lines, 25, y);
        y += lines.length * 6 + 2;
    });

    y += 5;

    // Recommendations
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Recommendations", 20, y);

    y += 10;

    pdf.setFont("helvetica", "normal");

    report.recommendations.forEach((item: string) => {
        const lines = pdf.splitTextToSize(`• ${item}`, 165);
        pdf.text(lines, 25, y);
        y += lines.length * 6 + 2;
    });

    // Footer
    pdf.setFontSize(10);
    pdf.text(
        "Generated by InsightForge AI",
        20,
        285
    );

    pdf.save("InsightForge_AI_Report.pdf");
}