import { jsPDF } from "jspdf";

export function downloadReportPDF(report: any) {
    const pdf = new jsPDF();

    let y = 20;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(22);
    pdf.text("InsightForge AI", 20, y);

    y += 10;

    pdf.setFontSize(16);
    pdf.text("Business Intelligence Report", 20, y);

    y += 8;

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Generated: ${report.generated_at}`, 20, y);

    y += 15;

    // Executive Summary
    pdf.setFontSize(15);
    pdf.setFont("helvetica", "bold");
    pdf.text("Executive Summary", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");

    const summary = pdf.splitTextToSize(
        report.executive_summary || "",
        170
    );

    pdf.text(summary, 20, y);

    y += summary.length * 6 + 10;

    // Dataset Quality
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Dataset Quality", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");

    const quality = pdf.splitTextToSize(
        report.data_quality || "",
        170
    );

    pdf.text(quality, 20, y);

    y += quality.length * 6 + 10;

    // Key Statistics
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Key Statistics", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");

    (report.key_findings|| []).forEach((item: string) => {
        const lines = pdf.splitTextToSize("• " + item, 165);
        pdf.text(lines, 25, y);
        y += lines.length * 6 + 2;
    });

    y += 6;

    // Business Insights
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Business Insights", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");

    (report.business_insights || []).forEach((item: string) => {
        const lines = pdf.splitTextToSize("• " + item, 165);
        pdf.text(lines, 25, y);
        y += lines.length * 6 + 2;
    });

    y += 6;

    // Recommendations
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Recommendations", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");

    (report.recommendations || []).forEach((item: string) => {
        const lines = pdf.splitTextToSize("• " + item, 165);
        pdf.text(lines, 25, y);
        y += lines.length * 6 + 2;
    });

    y += 8;

    // Conclusion
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("Conclusion", 20, y);

    y += 8;

    pdf.setFont("helvetica", "normal");

    const conclusion = pdf.splitTextToSize(
        report.conclusion || "",
        170
    );

    pdf.text(conclusion, 20, y);

    pdf.setFontSize(10);

    pdf.text(
        "Generated by InsightForge AI",
        20,
        285
    );

    pdf.save("InsightForge_AI_Report.pdf");
}