interface PdfReportProps {
    report: any;
  }
  
  export default function PdfReport({ report }: PdfReportProps) {
    if (!report) return null;
  
    return (
      <div
        id="pdf-report"
        className="bg-white text-black p-10 w-[794px] min-h-[1123px]"
      >
        {/* Header */}
        <div className="border-b-4 border-blue-600 pb-5">
          <h1 className="text-4xl font-bold text-blue-700">
            InsightForge AI
          </h1>
  
          <p className="text-gray-600 mt-2">
            AI-Powered Business Intelligence Platform
          </p>
  
          <p className="text-sm text-gray-500 mt-4">
            Generated on {new Date().toLocaleString()}
          </p>
        </div>
  
        {/* Executive Summary */}
        <section className="mt-8">
          <h2 className="text-2xl font-bold mb-3">
            Executive Summary
          </h2>
  
          <p className="leading-8">
            {report.executive_summary}
          </p>
        </section>
  
        {/* KPI Cards */}
        <section className="mt-10">
          <h2 className="text-2xl font-bold mb-5">
            Dataset Overview
          </h2>
  
          <div className="grid grid-cols-3 gap-5">
            {Object.entries(report.statistics).map(([key, value]) => (
              <div
                key={key}
                className="border rounded-xl shadow p-5"
              >
                <p className="text-gray-500 text-sm">{key}</p>
  
                <h3 className="text-3xl font-bold mt-2">
                  {String(value)}
                </h3>
              </div>
            ))}
          </div>
        </section>
  
        {/* Insights */}
        <section className="mt-10">
          <h2 className="text-2xl font-bold mb-4">
            AI Insights
          </h2>
  
          <ul className="space-y-3">
            {report.insights.map((item: string, index: number) => (
              <li key={index}>
                • {item}
              </li>
            ))}
          </ul>
        </section>
  
        {/* Recommendations */}
        <section className="mt-10">
          <h2 className="text-2xl font-bold mb-4">
            Business Recommendations
          </h2>
  
          <ul className="space-y-3">
            {report.recommendations.map((item: string, index: number) => (
              <li key={index}>
                • {item}
              </li>
            ))}
          </ul>
        </section>
  
        <div className="mt-16 text-center text-gray-500 text-sm">
          Generated by InsightForge AI
        </div>
      </div>
    );
  }