interface Report {
    title: string;
    executive_summary: string;

    dataset_quality: {
        rows: number;
        columns: number;
        memory: number;
        missing_values: number;
        duplicate_rows: number;
        quality_score: number;
        status: string;
    };

    key_statistics: Record<string, any>;

    business_insights: {
        title: string;
        description: string;
    }[];

    recommendations: {
        title: string;
        description: string;
        priority: string;
    }[];

    conclusion: string;
}

interface ReportViewerProps {
    report: Report | null;
}

export default function ReportViewer({
    report,
}: ReportViewerProps) {

    if (!report) {
        return (
            <div className="rounded-xl bg-slate-800 p-8 text-center text-slate-400">
                No report generated yet.
            </div>
        );
    }

    return (

        <div className="space-y-6">

            {/* Title */}

            <div className="rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 p-8 shadow-xl">

                <h1 className="text-3xl font-bold text-white">
                    {report.title}
                </h1>

                <p className="mt-2 text-blue-100">
                    Generated by InsightForge AI
                </p>

            </div>

            <Section
                title="📋 Executive Summary"
            >
                {report.executive_summary}
            </Section>

                <Section title="🟢 Dataset Quality">
                <>
                    Rows: {report.dataset_quality.rows}<br />
                    Columns: {report.dataset_quality.columns}<br />
                    Memory: {report.dataset_quality.memory} MB<br />
                    Missing Values: {report.dataset_quality.missing_values}<br />
                    Duplicate Rows: {report.dataset_quality.duplicate_rows}<br />
                    Quality Score: {report.dataset_quality.quality_score}%<br />
                    Status: {report.dataset_quality.status}
                </>
            </Section>

            <div className="rounded-2xl bg-slate-800 p-6 shadow-lg">
    <h2 className="mb-4 text-2xl font-bold text-white">
        📊 Key Statistics
    </h2>

    {Object.entries(report.key_statistics).map(([key, value]) => (
        <div
            key={key}
            className="mb-2 rounded-lg bg-slate-900 p-3 text-slate-300"
        >
            <strong>{key}</strong>: {String(value)}
        </div>
    ))}
</div>

<div className="rounded-2xl bg-slate-800 p-6 shadow-lg">
    <h2 className="mb-4 text-2xl font-bold text-white">
        💡 Business Insights
    </h2>

    {report.business_insights.map((item, index) => (
        <div
            key={index}
            className="mb-3 rounded-lg bg-slate-900 p-4"
        >
            <h3 className="font-bold text-white">
                {item.title}
            </h3>

            <p className="text-slate-300">
                {item.description}
            </p>
        </div>
    ))}
</div>

<div className="rounded-2xl bg-slate-800 p-6 shadow-lg">
    <h2 className="mb-4 text-2xl font-bold text-white">
        🚀 Recommendations
    </h2>

    {report.recommendations.map((item, index) => (
        <div
            key={index}
            className="mb-3 rounded-lg bg-slate-900 p-4"
        >
            <h3 className="font-bold text-white">
                {item.title}
            </h3>

            <p className="text-slate-300">
                {item.description}
            </p>

            <span className="text-sm text-blue-400">
                Priority: {item.priority}
            </span>
        </div>
    ))}
</div>

            <Section
                title="✅ Conclusion"
            >
                {report.conclusion}
            </Section>

        </div>

    );

}

function Section({
    title,
    children,
}: {
    title: string;
    children: React.ReactNode;
}) {

    return (

        <div className="rounded-2xl bg-slate-800 p-6 shadow-lg">

            <h2 className="mb-4 text-2xl font-bold text-white">
                {title}
            </h2>

            <p className="leading-8 text-slate-300">
                {children}
            </p>

        </div>

    );

}


