interface Report {
    title: string;
    executive_summary: string;
    dataset_quality: string;
    key_statistics?: string[];
    business_insights?: string[];
    recommendations?: string[];
    conclusion: string;
}

interface ReportViewerProps {
    report: Report | null;
}

export default function ReportViewer({
    report,
}: ReportViewerProps) {

    if (!report) {
        return (
            <div className="rounded-xl bg-slate-800 p-8 text-center text-slate-400">
                No report generated yet.
            </div>
        );
    }

    return (

        <div className="space-y-6">

            {/* Title */}

            <div className="rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 p-8 shadow-xl">

                <h1 className="text-3xl font-bold text-white">
                    {report.title}
                </h1>

                <p className="mt-2 text-blue-100">
                    Generated by InsightForge AI
                </p>

            </div>

            <Section
                title="📋 Executive Summary"
            >
                {report.executive_summary}
            </Section>

            <Section
                title="🟢 Dataset Quality"
            >
                {report.dataset_quality}
            </Section>

            <ListSection
                title="📊 Key Statistics"
                items={report.key_statistics}
            />

            <ListSection
                title="💡 Business Insights"
                items={report.business_insights}
            />

            <ListSection
                title="🚀 Recommendations"
                items={report.recommendations}
            />

            <Section
                title="✅ Conclusion"
            >
                {report.conclusion}
            </Section>

        </div>

    );

}

function Section({
    title,
    children,
}: {
    title: string;
    children: React.ReactNode;
}) {

    return (

        <div className="rounded-2xl bg-slate-800 p-6 shadow-lg">

            <h2 className="mb-4 text-2xl font-bold text-white">
                {title}
            </h2>

            <p className="leading-8 text-slate-300">
                {children}
            </p>

        </div>

    );

}

function ListSection({
    title,
    items,
}: {
    title: string;
    items: string[];
}) {

    return (

        <div className="rounded-2xl bg-slate-800 p-6 shadow-lg">

            <h2 className="mb-4 text-2xl font-bold text-white">
                {title}
            </h2>

            <ul className="space-y-3">

                {(items ?? []).map((item, index) => (

                    <li
                        key={index}
                        className="rounded-lg bg-slate-900 p-4 text-slate-300"
                    >
                        • {item}
                    </li>

                ))}

            </ul>

        </div>

    );

}